set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/tool_paths.cmake")
    include("${CMAKE_CURRENT_LIST_DIR}/tool_paths.cmake")
else()
    set(TOOLCHAIN_GCC_BIN    "${CMAKE_CURRENT_LIST_DIR}/../tools/gcc/bin")
    set(TOOLCHAIN_GCC_PREFIX "arm-none-eabi-")
    message(WARNING "cmake/tool_paths.cmake not found - run setup.ps1!")
endif()
set(TC "${TOOLCHAIN_GCC_BIN}/${TOOLCHAIN_GCC_PREFIX}")
set(CMAKE_C_COMPILER   "${TC}gcc.exe"     CACHE FILEPATH "C compiler")
set(CMAKE_CXX_COMPILER "${TC}g++.exe"     CACHE FILEPATH "C++ compiler")
set(CMAKE_ASM_COMPILER "${TC}gcc.exe"     CACHE FILEPATH "ASM compiler")
set(CMAKE_OBJCOPY      "${TC}objcopy.exe" CACHE FILEPATH "objcopy")
set(CMAKE_SIZE_UTIL    "${TC}size.exe"    CACHE FILEPATH "size")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)