if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/mcu_arch.txt")
    file(READ "${CMAKE_CURRENT_LIST_DIR}/mcu_arch.txt" MCU_ARCH_TXT)
    string(STRIP "${MCU_ARCH_TXT}" MCU_ARCH_TXT)
else()
    set(MCU_ARCH_TXT "ARM")
endif()
if(MCU_ARCH_TXT STREQUAL "RISCV")
    include("${CMAKE_CURRENT_LIST_DIR}/riscv-wch-elf.cmake")
else()
    include("${CMAKE_CURRENT_LIST_DIR}/arm-none-eabi.cmake")
endif()